### ISSUE TITLE
Deprecated function warnings with latest etherpad-lite.

### ISSUE THREAD

**Issue by kb1828** [ether/ep_headerauth#58]
ep_headerauth is logging the following warnings with etherpad-lite 2.1.0

```
[WARN] settings - the `client` context property for the handleMessageSecurity and handleMessage hooks is deprecated; use the `socket` property instead 
    at Object.get client (/opt/etherpad-lite/src/node/handler/PadMessageHandler.ts:306:16)
    at exports.handleMessage [as hook_fn] (/opt/etherpad-lite/src/plugin_packages/.versions/ep_headerauth@1.1.19/index.js:53:51)
    at /opt/etherpad-lite/src/static/js/pluginfw/hooks.js:272:18
    at new Promise (<anonymous>)
    at callHookFnAsync (/opt/etherpad-lite/src/static/js/pluginfw/hooks.js:235:16)
    at /opt/etherpad-lite/src/static/js/pluginfw/hooks.js:350:54
    at Array.map (<anonymous>)
    at exports.aCallAll (/opt/etherpad-lite/src/static/js/pluginfw/hooks.js:350:13)
    at Object.exports.handleMessage (/opt/etherpad-lite/src/node/handler/PadMessageHandler.ts:330:20)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at <anonymous> (/opt/etherpad-lite/src/node/handler/SocketIORouter.ts:84:14)
[WARN] settings - AuthorManager.getAuthor4Token() is deprecated; use AuthorManager.getAuthorId() instead 
    at Object.exports.getAuthor4Token (/opt/etherpad-lite/src/node/db/AuthorManager.ts:172:3)
    at exports.handleMessage [as hook_fn] (/opt/etherpad-lite/src/plugin_packages/.versions/ep_headerauth@1.1.19/index.js:79:40)
    at /opt/etherpad-lite/src/static/js/pluginfw/hooks.js:272:18
    at new Promise (<anonymous>)
    at callHookFnAsync (/opt/etherpad-lite/src/static/js/pluginfw/hooks.js:235:16)
    at /opt/etherpad-lite/src/static/js/pluginfw/hooks.js:350:54
    at Array.map (<anonymous>)
    at exports.aCallAll (/opt/etherpad-lite/src/static/js/pluginfw/hooks.js:350:13)
    at Object.exports.handleMessage (/opt/etherpad-lite/src/node/handler/PadMessageHandler.ts:330:20)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at <anonymous> (/opt/etherpad-lite/src/node/handler/SocketIORouter.ts:84:14)
```

**Comment by kb1828** [comment]
Not sure this is going to be addressed. CLosing.
